### ISSUE TITLE
Missing serviceAccountName for deployment if using service account to grant xray permission

### ISSUE THREAD

**Issue by zxkane** [aws-samples/aws-xray-kubernetes#10]
The xray-daemon yaml misses the `serviceAccountName` if using service account.

```yaml
  template:
    metadata:
      labels:
        app: xray-daemon
    spec:
     # add below line if using service account to grant xray permissions to pod
      serviceAccountName: xray-daemon 
      volumes:
        - name: config-volume
          configMap:
            name: "xray-config"
      containers:
```
